name: 'Fetch NONMEM'
description: 'Fetch a specific NONMEM version zip archive'
inputs:
  archive-artifact:
    description: 'The artifact name to use to upload the archive'
    required: true
  nonmem-version:
    description: 'The NONMEM version to install'
    required: false
    default: '7.5.1'

runs:
  using: "composite"
  steps:

    - name: Cache NONMEM fetch
      id: cache-nonmem-fetch
      uses: actions/cache@v3
      with:
          path: 751.zip
          key: nonmem-751

    - name: Fetch NONMEM
      if: steps.cache-nonmem-fetch.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt install lynx
        echo 'key /' >>lynxcmds
        echo 'key 7' >>lynxcmds
        echo 'key 5' >>lynxcmds
        echo 'key 1' >>lynxcmds
        echo 'key ^J' >>lynxcmds
        echo 'key ^J' >>lynxcmds
        echo 'key /' >>lynxcmds
        echo 'key z' >>lynxcmds
        echo 'key i' >>lynxcmds
        echo 'key p' >>lynxcmds
        echo 'key ^J' >>lynxcmds
        echo 'key d' >>lynxcmds
        echo 'key ^J' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key <delete>' >>lynxcmds
        echo 'key 7' >>lynxcmds
        echo 'key 5' >>lynxcmds
        echo 'key 1' >>lynxcmds
        echo 'key .' >>lynxcmds
        echo 'key z' >>lynxcmds
        echo 'key i' >>lynxcmds
        echo 'key p' >>lynxcmds
        echo 'key ^J' >>lynxcmds
        echo 'key Q' >>lynxcmds
        lynx -accept-all-cookies nonmem.iconplc.com -cmd_script=lynxcmds

    - name: Upload NONMEM ZIP file
      uses: actions/upload-artifact@v3
      with:
        retention-days: 1
        name: ${{ inputs.archive-artifact }}
        path: 751.zip
