name: 'Compile NONMEM on Windows'
inputs:
  archive-artifact:
    description: 'The artifact name to use to download the archive'
    required: true
  nonmem-zip-key:
    description: 'The NONMEM ZIP key'
    required: True
  nonmem-license-key:
    description: 'The NONMEM license key'
    required: True

runs:
  using: "composite"
  steps:
    # https://github.com/modflowpy/install-gfortran-action/blob/dfc32754e541304f2e7b7ca001e40dce094a5cd6/action.yml#L22-L30
    - name: Setup gfortran
      shell: bash
      run: |
        FCDIR=/c/ProgramData/Chocolatey/bin
        LNDIR=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin
        if [ -d "$FCDIR" ] && [ -f "$LNDIR/libgfortran-5.dll" ] && [ ! -f "$FCDIR/libgfortran-5.dll" ]; then
            ln -s "$LNDIR/libgfortran-5.dll" "$FCDIR/libgfortran-5.dll"
        fi

    - name: Fetch archive
      id: download
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.archive-artifact }}

    - name: Unzip NONMEM
      shell: cmd
      env:
        SECRET_ZIP_KEY: ${{ inputs.nonmem-zip-key }}
      run: 7z x 751.zip -p%SECRET_ZIP_KEY%

    - name: Copy NONMEM license
      shell: bash
      run: echo $SECRET_LICENSE_KEY > nm751CD/nonmem.lic
      env:
        SECRET_LICENSE_KEY: ${{ inputs.nonmem-license-key }}

    - name: Build NONMEM
      shell: cmd
      run: |
        set INSTALLDIR=%CD%\nm751
        cd nm751CD
        SETUP75.bat %CD% %INSTALLDIR% gfortran y ar same rec q
